apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zp6taxglg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zp6taxglg-go 
  name: zp6taxglg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zp6taxglg-go 
